### ISSUE TITLE
Crashes on loading training mode.

### ISSUE THREAD

**Issue by chaid-s** [Eiton/MBTL-Hitbox-Viewer#1]
Release 1.4.6 currently crashes on loading training mode. Training mode loads fine without d3d9.dll and MBTL_hitbox_overlay.dll in \MELTY BLOOD TYPE LUMINA folder.

**Comment by Eiton** [comment]
I assume the previous version works before the game update broke it.
Have you installed the newest game update?
Is it happening on all characters on all stages?
Does it work on other modes?
What is your OS version and hardware spec?

**Comment by chaid-s** [comment]
I managed to revolve the crashing issue by reinstalling the game.

Though, prior to this, It didn't work in any other mode with any of the characters. My game was fully updated and all prior releases had worked.
